name: Lint and Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      # Installation/setup steps
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint
      - name: Install Helm
        run: |
          wget https://get.helm.sh/helm-v2.11.0-linux-amd64.tar.gz
          tar -zxvf helm-v2.11.0-linux-amd64.tar.gz
          sudo cp linux-amd64/helm /usr/local/bin/helm
      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo cp kubeval /usr/local/bin
      - name: Install git-crypt
        run: |
          git clone https://github.com/AGWA/git-crypt.git
          cd git-crypt
          make
          make install PREFIX=${PWD}
      - name: Unlock secrets
        run: |
          git-crypt/git-crypt unlock ${{ secrets.gitcryptSecret }}

      # Now lint and validate the helm chart for each cluster
      - name: Lint and Validate staging
        run: |
          python scripts/lint-and-validate.py --values config/staging.yaml secrets/config/staging.yaml secrets/config/common.yaml

      - name: Lint and Validate prod
        run: |
          python scripts/lint-and-validate.py --values config/prod.yaml secrets/config/prod.yaml secrets/config/common.yaml

      - name: Lint and Validate OVH
        run: |
          python scripts/lint-and-validate.py --values config/ovh.yaml secrets/config/ovh.yaml secrets/config/common.yaml

      - name: Lint and Validate Turing
        run: |
          python scripts/lint-and-validate.py --values config/turing.yaml secrets/config/turing.yaml secrets/config/common.yaml

      - name: Clean up
        if: always()  # Always run this step
        run: |
          rm -rf scripts/rendered-templates
